[server]
address = "localhost"
headless = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#6C63FF"
backgroundColor = "#12121e"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#CCCCCC"
